### ISSUE TITLE
use Oblique with Glide

### ISSUE THREAD

**Issue by hymanme** [akshay2211/Oblique#3]
I use Glide....into(obliqueView);but have no effect,i just got en empty image.

**Comment by akshay2211** [comment]
hello @hymanme
You can do that by 

`Glide
    .with(getApplicationContext())
    .load("https://raw.githubusercontent.com/akshay2211/Oblique/master/media/one.png")
    .asBitmap()
    .into(new SimpleTarget<Bitmap>(200,200) {
        @Override
        public void onResourceReady(Bitmap resource, GlideAnimation glideAnimation) {
              obliqueView.setImageBitmap(resource);
        }
    });`
