### ISSUE TITLE
Where is the gray color?

### ISSUE THREAD

**Issue by nuhkoca** [akshay2211/Oblique#5]
Hi Akshay,

First of all, many thanks for such a good library!

I imported your library successfully but I am actually facing an issue which the gray color not appearing. Do you know why?

![screen shot 2017-08-15 at 22 19 47](https://user-images.githubusercontent.com/5719389/29332308-444852ee-8208-11e7-8427-1ebc8eb6d2c0.png)

**Comment by akshay2211** [comment]
Hello @nuhkoca 
Thank you for trying this project
that grey color was there because of the default theme of android
I've updated the code as well, so pull the project again and it will be resolved.
