### ISSUE TITLE
some problems

### ISSUE THREAD

**Issue by Hitexroid** [akshay2211/Oblique#7]
Hi
When i add `ObliqueView` into `xml` , not showing any image.
`xml` code :

```
    <ak.sh.ay.oblique.ObliqueView
        android:id="@+id/obliqueView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_below="@+id/check"
        android:layout_margin="20dp"
        android:layout_weight="1"
        android:scaleType="centerCrop"
        android:src="@drawable/pretty_1"
        app:ending_slant_angle="0"
        app:starting_slant_angle="0"
        app:type="image" />
```

when i add `ObliqueView` programmatically  , `setType` not work , `setStartAngle(x)` and `setEndAngle(x)` just works in `onCreate` , and not works in `Seekbar` listener.

**Comment by akshay2211** [comment]
Hello @Hitexroid  
can u show me the full code where u are using this 
or kindly refer the sample as all the raised issues are not present in it.
thank you.
